//lua generated
#include "tables.h"

std::map<std::string, uint8_t> asmTable{
    {"nop", 0},
    {"mov", 1},
    {"goto", 2},
    {"ptov", 3},
    {"jifn", 4},
    {"spsh", 5},
    {"spop", 6},
    {"fncr", 7},
    {"fnrt", 8},
    {"get", 9},
    {"putc", 10},
    {"putp", 11},
    {"quit", 12},
    {"add", 65},
    {"sub", 66},
    {"div", 67},
    {"mod", 68},
    {"mul", 69},
    {"eql", 70},
    {"less", 71},
    {"and", 72},
    {"or", 73},
    {"not", 74},
    {"bxor", 75},
    {"band", 76},
    {"bor", 77},
    {"bnot", 78},
    {"bshl", 79},
    {"bshr", 80},
};

std::map<std::string, uint8_t> regTable{
    {"null", 0},
    {"inn", 8},
    {"rinf", 12},
    {"sptr", 16},
    {"fndt", 20},
    {"fa", 24},
    {"fb", 32},
    {"fc", 40},
    {"ia", 48},
    {"ib", 52},
    {"ic", 56},
    {"ca", 60},
    {"cb", 61},
    {"cc", 62},
    {"cd", 63},
};